//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoMurica
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminInfo()
        {
            this.AdminLoginCreds = new HashSet<AdminLoginCred>();
            this.SuspendedAccounts = new HashSet<SuspendedAccount>();
        }
    
        public string AdminID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        //public void SetFields() { };


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminLoginCred> AdminLoginCreds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuspendedAccount> SuspendedAccounts { get; set; }
    }
}
