//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoMurica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BomDBEntities1 : DbContext
    {
        public BomDBEntities1()
            : base("name=BomDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminInfo> AdminInfoes { get; set; }
        public virtual DbSet<AdminLoginCred> AdminLoginCreds { get; set; }
        public virtual DbSet<ATM> ATMs { get; set; }
        public virtual DbSet<CheckingAccount> CheckingAccounts { get; set; }
        public virtual DbSet<ClientInfo> ClientInfoes { get; set; }
        public virtual DbSet<ClientLoginCred> ClientLoginCreds { get; set; }
        public virtual DbSet<CreditLineAccount> CreditLineAccounts { get; set; }
        public virtual DbSet<MortgageAccount> MortgageAccounts { get; set; }
        public virtual DbSet<SavingAccount> SavingAccounts { get; set; }
        public virtual DbSet<SuspendedAccount> SuspendedAccounts { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
