//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoMurica
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClientInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientInfo()
        {
            this.CheckingAccounts = new HashSet<CheckingAccount>();
            this.ClientLoginCreds = new HashSet<ClientLoginCred>();
            this.CreditLineAccounts = new HashSet<CreditLineAccount>();
            this.MortgageAccounts = new HashSet<MortgageAccount>();
            this.SavingAccounts = new HashSet<SavingAccount>();
            this.SuspendedAccounts = new HashSet<SuspendedAccount>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }

        internal void SetClientId()
        {
            using (BomDBEntities1 bomDb = new BomDBEntities1())
            {
                var count = bomDb.ClientInfoes.Count() + 1;
                this.ClientID = this.LastName.Substring(0, 2) + "00" + count;
            }
        }

        internal void AddClient(int pass)
        {
            ClientLoginCred clientCreds = new ClientLoginCred();
            clientCreds.ClientID = this.ClientID;
            clientCreds.UserCode = this.LastName.Substring(0, 2) + this.Phone.Substring(0, 4);
            clientCreds.ClPassword = pass;
            using (BomDBEntities1 bomDb = new BomDBEntities1())
            {
                bomDb.ClientInfoes.Add(this);
                bomDb.ClientLoginCreds.Add(clientCreds);
                bomDb.SaveChanges();
            }
        }


    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckingAccount> CheckingAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLoginCred> ClientLoginCreds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditLineAccount> CreditLineAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MortgageAccount> MortgageAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavingAccount> SavingAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuspendedAccount> SuspendedAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
