//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoMurica
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SuspendedAccount
    {
        public int CaseId { get; set; }
        public string ClientID { get; set; }
        public string AccountID { get; set; }
        public string AdminID { get; set; }

        public virtual AdminInfo AdminInfo { get; set; }
        public virtual ClientInfo ClientInfo { get; set; }


        internal void SetValues(String cID, String acID, String adID)
        {
            var count = 0;
            using (BomDBEntities1 bomDb = new BomDBEntities1())
            {
                count = bomDb.SuspendedAccounts.Count() + 1;
            }
            this.CaseId = count;
            this.ClientID = cID;
            this.AccountID = acID;
            this.AdminID = adID;
        }

        internal void SuspendAccount()
        {
            using (BomDBEntities1 bomDb = new BomDBEntities1())
            {
                bomDb.SuspendedAccounts.Add(this);
                bomDb.SaveChanges();
            }
        }

        internal void ActivateAccount()
        {
            using (BomDBEntities1 bomDb = new BomDBEntities1())
            {
                bomDb.SuspendedAccounts.Remove(this);
                bomDb.SaveChanges();
            }
        }
    }
}
