//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoMurica
{
    using BoMurica.BMModels;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public string ClientID { get; set; }
        public string AccountID { get; set; }
        public decimal Amount { get; set; }
        public bool Outbound { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
    
        public virtual ClientInfo ClientInfo { get; set; }

        internal void SetValues(TransactionData data)
        {
            var count = 0;
            using (BomDBEntities1 bomDb = new BomDBEntities1())
            {
                count = bomDb.Transactions.Count() + 1;
            }
            this.TransactionId = count;
            this.ClientID = data.ClientId;
            this.AccountID = data.Source;
            this.Amount = data.Amount;
            this.Outbound = data.Out;
            this.Receiver = data.Destination;
            this.EventTime = DateTime.Now;            
        }
        internal void AddTransaction()
        {
            using (BomDBEntities1 bomDb = new BomDBEntities1())
            {
                bomDb.Transactions.Add(this);
                bomDb.SaveChanges();
            }
        }
    }
}
